name: Cura Installer
run-name: ${{ inputs.cura_conan_version }} for ${{ inputs.platform }} by @${{ github.actor }}

on:
    workflow_call:
        inputs:
            platform:
                description: 'Selected Installer OS'
                default: 'ubuntu-20.04'
                required: true
                type: string
            os_name:
                description: 'OS Friendly Name'
                default: 'linux'
                required: true
                type: string
            cura_conan_version:
                description: 'Cura Conan Version'
                # must match format cura/[0-9].[0-9].[0-9]@whatever
                # and the version numbers must match the version number in the first line of the conandata.yml file
                default: 'cura/5.4.0@mehtaheino/main'
                required: true
                type: string


env:
    CURA_CONAN_VERSION: ${{ inputs.cura_conan_version }}
    TOKEN_GITHUB: ${{ secrets.GITHUB_TOKEN }}
    MAC_NOTARIZE_USER: ${{ secrets.MAC_NOTARIZE_USER }}
    MAC_NOTARIZE_PASS: ${{ secrets.MAC_NOTARIZE_PASS }}
    MACOS_CERT_P12: ${{ secrets.MACOS_CERT_P12 }}
    MACOS_CERT_INSTALLER_P12: ${{ secrets.MACOS_CERT_INSTALLER_P12 }}
    MACOS_CERT_USER: ${{ secrets.MACOS_CERT_USER }}
    MACOS_CERT_PASSPHRASE: ${{ secrets.MACOS_CERT_PASSPHRASE }}
    GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
    CODESIGN_IDENTITY: ${{ secrets.CODESIGN_IDENTITY }}












jobs:
    cura-installer-create:
        runs-on: ${{ inputs.platform }}
        steps:
            -   name: Checkout
                uses: actions/checkout@v3


            -   name: Checkout engine
                uses: actions/checkout@v3
                with:
                    repository: mehtaheino/CuraEngine
                    token: ${{ secrets.GITHUB_TOKEN }}
                    path: CuraEngine

            -   name: Checkout materials
                uses: actions/checkout@v3
                with:
                    repository: mehtaheino/fdm_materials-for-MANU
                    token: ${{ secrets.GITHUB_TOKEN }}
                    path: fdm_materials

            -   name: Setup Python and pip
                uses: actions/setup-python@v4
                with:
                    python-version: '3.10.x'
                    cache: 'pip'
                    cache-dependency-path: .github/workflows/requirements-conan-package.txt

            -   name: Install Python requirements for runner
                run: pip install -r https://raw.githubusercontent.com/mehtaheino/Cura-for-MANU/main/.github/workflows/requirements-conan-package.txt
                #  Note the runner requirements are always installed from the main branch in the Ultimaker/Cura repo

            -   name: Install MacOS system requirements
                if:  ${{ runner.os == 'Macos' }}
                run: brew install autoconf automake ninja create-dmg # Delete create-dmg when deprecating dmg
                
                #install linux system requirements
            -   name: Hack needed specifically for ubuntu-22.04 from mid-Feb 2023 onwards
                if: ${{ runner.os == 'Linux' && startsWith(inputs.platform, 'ubuntu-22.04') }}
                run: sudo apt remove libodbc2 libodbcinst2 unixodbc-common -y

            # NOTE: Due to what are probably github issues, we have to remove the cache and reconfigure before the rest.
            #       This is maybe because grub caches the disk it uses last time, which is recreated each time.
            -   name: Install Linux system requirements
                if: ${{ runner.os == 'Linux' }}
                run: |
                    sudo rm /var/cache/debconf/config.dat
                    sudo dpkg --configure -a
                    sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
                    sudo apt update
                    sudo apt upgrade
                    sudo apt install build-essential checkinstall libegl-dev zlib1g-dev libssl-dev ninja-build autoconf libx11-dev libx11-xcb-dev libfontenc-dev libice-dev libsm-dev libxau-dev libxaw7-dev libxcomposite-dev libxcursor-dev libxdamage-dev libxdmcp-dev libxext-dev libxfixes-dev libxi-dev libxinerama-dev libxkbfile-dev libxmu-dev libxmuu-dev libxpm-dev libxrandr-dev libxrender-dev libxres-dev libxss-dev libxt-dev libxtst-dev libxv-dev libxvmc-dev libxxf86vm-dev xtrans-dev libxcb-render0-dev libxcb-render-util0-dev libxcb-xkb-dev libxcb-icccm4-dev libxcb-image0-dev libxcb-keysyms1-dev libxcb-randr0-dev libxcb-shape0-dev libxcb-sync-dev libxcb-xfixes0-dev libxcb-xinerama0-dev xkb-data libxcb-dri3-dev uuid-dev libxcb-util-dev libxkbcommon-x11-dev pkg-config -y
                    wget --no-check-certificate --quiet https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage -O $GITHUB_WORKSPACE/appimagetool
                    chmod +x $GITHUB_WORKSPACE/appimagetool
                    echo "APPIMAGETOOL_LOCATION=$GITHUB_WORKSPACE/appimagetool" >> $GITHUB_ENV

            -   name: Install GCC-12 on ubuntu-22.04
                if: ${{ startsWith(inputs.platform, 'ubuntu-22.04') }}
                run: |
                    sudo apt install g++-12 gcc-12 -y
                    sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-12 12
                    sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-12 12

            -   name: Use GCC-10 on ubuntu-20.04
                if: ${{ startsWith(inputs.platform, 'ubuntu-20.04') }}
                run: |
                    sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 10
                    sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 10
             
                #end linux install block

            -   name: Create the default Conan profile
                run:  conan profile new default --detect

            -   name: Get Conan configuration
                if: ${{ inputs.conan_config == '' }}
                run: conan config install https://github.com/ultimaker/conan-config.git

            -   name: create conan Engine package (powershell)
                working-directory: CuraEngine
                run: conan create . curaengine/5.0.1@mehtaheino/main --build=missing --update

            -   name: create conan materials package (powershell)
                working-directory: fdm_materials
                run: conan create . fdm_materials/5.0.1@mehtaheino/master --build=missing --update

            -   name: create conan package (bash)
                if: ${{ runner.os != 'Windows' }}
                run: conan create . $CURA_CONAN_VERSION --build=missing --update

            -   name: create conan package (powershell)
                if: ${{ runner.os == 'Windows' }}
                run: conan create . $Env:CURA_CONAN_VERSION --build=missing --update

            -   name: Install the Packages (Powershell)
                if: ${{ runner.os == 'Windows' }}
                run: conan install $Env:CURA_CONAN_VERSION --build=missing --update -if cura_inst -g VirtualPythonEnv --json "cura_inst/conan_install_info.json" --require-override=fdm_materials/5.0.1@mehtaheino/master

            -   name: Create the Packages (Bash)
                if: ${{ runner.os != 'Windows' }}
                run: conan install $CURA_CONAN_VERSION --build=missing --update -if cura_inst -g VirtualPythonEnv --json "cura_inst/conan_install_info.json" --require-override=fdm_materials/5.0.1@mehtaheino/master

            -   name: Set Environment variables for Cura (bash)
                if: ${{ runner.os != 'Windows' }}
                run: |
                    . ./cura_inst/bin/activate_github_actions_env.sh
                    . ./cura_inst/bin/activate_github_actions_version_env.sh

            -   name: Set Environment variables for Cura (Powershell)
                if: ${{ runner.os == 'Windows' }}
                run: |
                    echo "${Env:WIX}\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
                    .\cura_inst\Scripts\activate_github_actions_env.ps1
                    .\cura_inst\Scripts\activate_github_actions_version_env.ps1


                # FIXME: This is a workaround to ensure that we use and pack a shared library for OpenSSL 1.1.1l. We currently compile
                #  OpenSSL statically for CPython, but our Python Dependenies (such as PyQt6) require a shared library.
                #  Because Conan won't allow for building the same library with two different options (easily) we need to install it explicitly
                #  and do a manual copy to the VirtualEnv, such that Pyinstaller can find it.


            -   name: Install OpenSSL shared
                run: conan install openssl/1.1.1l@_/_ --build=missing --update -o openssl:shared=True -g deploy

            -   name: Copy OpenSSL shared (Bash)
                if: ${{ runner.os != 'Windows' }}
                run: |
                    cp ./openssl/lib/*.so* ./cura_inst/bin/ || true
                    cp ./openssl/lib/*.dylib* ./cura_inst/bin/ || true


            -   name: Copy OpenSSL shared (Powershell)
                if: ${{ runner.os == 'Windows' }}
                run: |
                    cp openssl/bin/*.dll ./cura_inst/Scripts/
                    cp openssl/lib/*.lib ./cura_inst/Lib/

            -   name: Create the Cura dist
                run: pyinstaller ./cura_inst/UltiMaker-Cura.spec

            -   name: Output the name file name and extension
                id: filename
                shell: python
                run: |
                    import os
                    installer_filename = f"MehtaHeino-Cura-{os.getenv('CURA_VERSION_FULL')}-${{ inputs.os_name }}"
                    if "${{ runner.os }}" == "Windows":
                        installer_ext = "msi" if "${{ inputs.msi_installer }}" == "true" else "exe"
                    elif "${{ runner.os }}" == "macOS":
                        installer_ext = "pkg" if "${{ inputs.msi_installer }}" == "true" else "dmg"
                    else:
                        installer_ext = "AppImage"
                    output_env = os.environ["GITHUB_OUTPUT"]
                    content = ""
                    if os.path.exists(output_env):
                        with open(output_env, "r") as f:
                            content = f.read()
                    with open(output_env, "w") as f:
                        f.write(content)
                        f.writelines(f"INSTALLER_FILENAME={installer_filename}\n")
                        f.writelines(f"INSTALLER_EXT={installer_ext}\n")
                        f.writelines(f"FULL_INSTALLER_FILENAME={installer_filename}.{installer_ext}\n")

            -   name: Create the Windows exe installer (Powershell)
                if: ${{ runner.os == 'Windows' }}
                run: |
                    python ..\cura_inst\packaging\NSIS\create_windows_installer.py ../cura_inst . "${{ steps.filename.outputs.FULL_INSTALLER_FILENAME }}"
                working-directory: dist

            -   name: Create the MacOS dmg and/or pkg (Bash)
                if: ${{ runner.os == 'Macos' }}
                run: python ../cura_inst/packaging/MacOS/build_macos.py ../cura_inst . $CURA_CONAN_VERSION "${{ steps.filename.outputs.FULL_INSTALLER_FILENAME }}" "$CURA_APP_NAME"
                working-directory: dist
                
            -   name: Create the AppImage for Linux (Bash)
                if: ${{ runner.os == 'Linux' }}
                run: python ../cura_inst/packaging/AppImage/create_appimage.py . $CURA_CONAN_VERSION "${{ steps.filename.outputs.FULL_INSTALLER_FILENAME }}"
                working-directory: dist

            -   name: Upload the artifacts
                uses: actions/upload-artifact@v3
                with:
                    name: ${{ steps.filename.outputs.INSTALLER_FILENAME }}-${{ steps.filename.outputs.INSTALLER_EXT }}
                    path: |
                        dist/*.tar.gz
                        dist/*.zip
                        dist/*.exe
                        dist/*.asc
                        dist/*.dmg
                    retention-days: 5
